myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from myblogs import urls as myblogs_urls
from users import urls as users_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myblogs/', include(myblogs_urls)),
    path('users/', include(users_urls)),
]

myblogs/urls.py
from django.urls import path
from . import views

app_name = 'myblogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_blog', views.add_blog, name='add_blog'),
    path('blog/<int:blog_id>', views.blog, name='blog'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import login
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', login,
         {'template_name': 'users/login.html'}, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),

]

myblogs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class BlogItems(models.Model):
    """single blog"""
    id = models.IntegerField(auto_created=True, primary_key=True)
    title = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=None)
    content = models.CharField(max_length=800)
    date_added = models.DateField(auto_now_add=True)
    is_del = models.IntegerField(default=0)

    def __str__(self):
        return "myblog:"+self.title

users/models.py
from django.db import models

# Create your models here.

myblogs/forms.py
from django import forms
from .models import BlogItems


class BlogItemForm(forms.ModelForm):
    class Meta:
        model = BlogItems
        fields = ['title', 'content']
        labels = {'title': '', 'content': ''}
        widgets = {
            'content': forms.Textarea(
                attrs={'cols': 100, 'rows': 10, 'max_length': 500, 'placeholder': 'input blog content', 'class': 'form-control'}),
            'title': forms.TextInput(attrs={'placeholder': 'input blog title', 'class': 'form-control'})}

myblogs/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from .models import BlogItems
from .forms import BlogItemForm
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required
def index(request):
    blogs = BlogItems.objects.filter(
        owner=request.user).order_by('-date_added')
    context = {}
    context['items'] = blogs
    return render(request, 'myblogs/index.html', context)


def add_blog(request):
    """add new blog"""
    if request.method != 'POST':
        form = BlogItemForm()
    else:
        form = BlogItemForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return HttpResponseRedirect(reverse('myblogs:index'))
    context = {'form': form}
    return render(request, 'myblogs/add_blog.html', context)


@login_required
def blog(request, blog_id):
    context = {}
    try:
        blog = BlogItems.objects.get(id=blog_id)
        context['blog'] = blog
        return render(request, 'myblogs/blog.html', context)
    except:
        return HttpResponse(" Can't find the blog, have you ever delete it before ")

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(
                username=new_user.username, password=request.POST['password']
            )
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('myblogs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('myblogs:index'))

myblogs/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'myblogs/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{%static 'myblogs/css/blogstyle.css'%}">
    <script src="{%static 'myblogs/jquery.js'%}"></script>
    <script src="{%static 'myblogs/js/bootstrap.js'%}"></script>
</head>

<body class='bg-dark'>
    <nav class="navbar navbar-light navbar-expand-lg bg-info">
        <a href="#" class='navbar-brand'>
            <!-- <div class="icondiv"></div> -->
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a href="{% url 'myblogs:index'%}" class="nav-item nav-link text-white">myBlogs</a>
                <a href="#" class="nav-item nav-link text-white">Blog Playground</a>
                <a href="#" class="nav-item nav-link text-white">MyProfile</a>
            </div>
        </div>
        <ul class="navbar-nav mr-autotext-white">
            {%if user.is_authenticated%}
            <li class="nav-item">
                <a href="#" class="nav-link text-white">welcome, {{user.username}}</a>
            </li>
            <li class="nav-item">
                <a href="{%url 'users:logout'%}" class="nav-link text-white">Logout</a>
            </li>
            {%else%}
            <li class="nav-item">
                <a href="{%url 'users:register'%}" class="nav-link text-white">Regist</a>
            </li>
            <li class="nav-item">
                <a href="{%url 'users:login'%}" class="nav-link text-white">
                    Login
                </a>
            </li>
            {%endif%}
        </ul>
    </nav>
    {%block content%}{%endblock content%}
    <!-- <p>footer</p> -->
</body>

</html>

myblogs/templates/myblogs/add_blog.html
{%extends 'base.html'%} {%block content%}

<div class="container ">
    <div class="row">
        <h2>add new blog</h2>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="{% url 'myblogs:add_blog'%}" method="POST">
                {%csrf_token%} {{form.as_p}}
                <a class='btn btn-warning float-right ml-2' href="{%url 'myblogs:index'%}">quit to main</a>
                <button name="submit" class='btn btn-primary float-right'>add Blog</button>
            </form>
        </div>
    </div>
</div>
{%endblock content%}

myblogs/templates/myblogs/blog.html
{%extends 'base.html'%} {%block content%}
<div class="container">
    <div class="card mt-5">
        <div class="card-header">
            {{blog.title}}
        </div>
        <div class="card-body">
            {{blog.content}}
        </div>
        <div class="card-footer">
            <a class="btn btn-success text-white" href="{%url 'myblogs:add_blog'%}">+ Add</a>
            <a class="btn btn-warning text-white">- Remove</a>
            <a class="btn btn-primary text-white">Edit</a>
        </div>
    </div>
</div>
{%endblock content%}

myblogs/templates/myblogs/index.html
{%extends 'base.html'%} {%block content%}
<div class="container">
    {%for item in items%}
    <div class="row">
        <div class="card col-md-12 mt-2 bg-light">
            <div class="card-body">
                <div class="card-title">
                    <h5>{{item.title}}</h5>
                    <small>{{item.date_added}}</small>
                </div>
                <div class="card-text">
                    {{item.content|truncatewords:50}}...
                </div>
                <small>
                    <a href="{%url 'myblogs:blog' item.id%}">learn more >></a>
                </small>
            </div>
        </div>
    </div>
    {%empty%}
    <h2>there is no blog has written</h2>
    {%endfor%}
    <div class="row">
        <div class="col-md-4 center mt-2">
            <a class="btn btn-primary" href="{%url 'myblogs:add_blog'%}">
                add new blog
            </a>
        </div>
    </div>
</div>
{%endblock content%}

users/templates/users/login.html
{%extends 'base.html'%} {%block header%}
<h2>Login to your account</h2>
{%endblock header%} {%block content%}
<div class="container">
    <div class="col-md4 offset-md-4 mt-5">
        <form method='POST' action="{%url 'users:login'%}">
            {%csrf_token%} {{form.as_p}}
            <button class='btn btn-primary'>Login</button>
            <input type="hidden" name="next" value="{%url 'myblogs:index'%}">
        </form>
    </div>
</div>
{%endblock content%}

users/templates/users/register.html
{%extends 'base.html'%}{%block content%}
<div class="container">
    <form action="{%url 'users:register'%}" method='POST' class='form-control'>
        {%csrf_token%}{{form.as_p}}
        <button name='submit' class='btn btn-success'>Regist User</button>
        <input type="hidden" name="text" value="{%url 'myblogs:index'%}">
    </form>
</div>
{%endblock content%}